### ISSUE TITLE
Have someone take a look at the design

### ISSUE THREAD

**Issue by henriyli** [sarukuku/mis#29]
It looks a bit crude. Please help!

**Comment by mbonilla-reaktor** [comment]
After a talk with Edwin, he helped to have this design as a more friendly dashboard:
![image](https://user-images.githubusercontent.com/57397687/70250160-c6177b80-177d-11ea-9fbd-cd234d9e185d.png)

card style (shadow):
```
.MuiPaper-elevation1 {
    box-shadow: 0px 0px 30px 10px rgba(0,0,0,0.05);
}```
